// Package webviewlib carries the native webview library (libwebview.so,
// libwebview.dylib or webview.dll) that napp windows load, so the launcher
// can put it on disk itself.
//
// go-webview's own embedded package used to do that from the child's init:
// it wrote the library into a shared os.TempDir()/webview-<version>
// directory, only if nothing was there yet, and pointed WEBVIEW_PATH (or, on
// Windows, PATH) at it. Any local account could pre-plant a library there
// and have it mapped into every napp window. Instead the launcher extracts
// these bytes through childbin.Ensure into the same verified per-user
// directory as the child program, re-hashes them before every spawn and
// passes that directory to the child as WEBVIEW_PATH.
//
// The bytes come from the pinned go-webview module: lib/ is generated by
// `go generate ./internal/webviewlib` (or `just webview-libs`) and is
// git-ignored, never committed. Run go generate with GOOS and GOARCH unset,
// because go run builds the copy program for the host. A test fails when the
// copies differ from the module's files.
//
// Every build of the launcher, dev and prod alike, embeds the library for its
// target. Targets without a library get nil Data, which childbin.Ensure
// refuses, so a napp window fails closed instead of loading something else.
package webviewlib

//go:generate go run ./gen

import (
	"crypto/sha256"
	"sync"
)

// sum hashes Data once per process; the bytes cannot change while the
// launcher runs.
var sum = sync.OnceValue(func() [32]byte { return sha256.Sum256(Data) })

// Sum is sha256(Data).
func Sum() [32]byte { return sum() }
